#ifndef __define_H__ 
#define __define_H__ 
/***********单片机系统头文件库************/
#include "HC89F30xC.h"
#include "HC89F30xC_SYS.h"
#include "HC89F30xC_IO_INIT.h"
#include "HC89F30xC_GeneralKey_Touch_Lib_V3.01\HC89F30xC_GeneralKey_Touch_Lib.h"
#include "HC89F30xC_GeneralKey_Touch_Lib_V3.01\HC89F30xC_GeneralKey_Touch_Auxiliary.h"
#include "HC89F30xC_TouchUartDebug_Lib_V2.00\HC89F30xC_TouchUartDebug_Lib_CFG.h"
#include "HC89F30xC_TouchUartDebug_Lib_V2.00\HC89F30xC_TouchUartDebug_Lib.h"

/***************用户自定义头文件库***********************/
#include "WDT.h"
#include "Buzzer_Driver.h"
#include "display.h"
#include "TM1652.h"
#include "TIMER.h"
#include "E2PROM_R_W.H"
#include "MATH.h"
#include "AD_TDS.h"
#include "Fun_Handle.h"
#include "KEY.h"
#include "USART.h"
#include "RS485.h"


#endif